//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace slnCrudEmpleadoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int cod_emp { get; set; }
        public string name_emp { get; set; }
        public string last_name_emp { get; set; }
        public string user_emp { get; set; }
        public string pass_emp { get; set; }
    }
}
